apiVersion: apps/v1
kind: Deployment
metadata:
  name: zhohno
  labels:
    app: zhohno
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1727197512279
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zhohno
  template:
    metadata:
      labels:
        app: zhohno
    spec:
      containers:
        - name: zhohno
          image: acrworkflow1727197512279.azurecr.io/image-workflow-1727197512279:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
