apiVersion: v1
kind: Service
metadata:
  name: zhohno
  namespace: namespace-workflow-1727197512279
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: zhohno
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000