apiVersion: v1
kind: Service
metadata:
  name: synergy
  namespace: namespace-workflow-1727251741140
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: synergy
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000