apiVersion: v1
kind: Service
metadata:
  name: energy
  namespace: namespace-workflow-1727255034610
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: energy
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000